### ISSUE TITLE
Crashdump

### ISSUE THREAD

**Issue by mneumann** [jesperes/erlang_1brc#3]
Hm, does this work with arbitrary number of cities? Have you tried with random city names? The Java 1brc createMeasurements creates random 10k cities.

**Comment by mneumann** [comment]
So to say, if I run your code, I am getting:

```
Runtime terminating during boot ({{nocatch,{name_clash,8786,<<"ana">>,<<"efa">>}},[{erlang_1brc,map_cities0,2,[{file,"src/erlang_1brc.erl"},{line,153}]},{timer,tc,2,[{file,"timer.erl"},{line,270}]},{erlang_1brc,run,1,[{file,"src/erlang_1brc.erl"},{line,100}]},{init,start_em,1,[]},{init,do_boot,3,[]}]})
```

Seems that your hash function is not "perfect".

**Comment by jesperes** [comment]
The hash function was home-made and, of course, crap. I've updated it to use Fnv32 now, and it should perform better (with less collisions).

Also, the Java 1brc does not actually create 10k cities (as far as I can tell). The *rules* say that your solution must be able to handle 10k cities. Also, you need to handle cities up to 100 bytes long.
